ChouettesBundle\Entity\Modele:
    type: entity
    table: null
    repositoryClass: ChouettesBundle\Repository\ModeleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        contenu:
            type: text
        lien:
            type: text
            nullable: true
        add_block:
            type: boolean

    manyToOne:
        categorie:
            targetEntity: ChouettesBundle\Entity\Categorie
        image:
            targetEntity: ChouettesBundle\Entity\Image
            cascade: ["persist", "remove"]
    lifecycleCallbacks: {  }
