#Routing de base
chouettes:
    resource: "@ChouettesBundle/Resources/config/routing.yml"
    prefix:   /
    schemes:   ['%http_protocol%']

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    schemes:   ['%http_protocol%']