modele_index:
    path:     /
    defaults: { _controller: "ChouettesBundle:Modele:index" }
    methods:  GET

modele_show:
    path:     /{id}/show
    defaults: { _controller: "ChouettesBundle:Modele:show" }
    methods:  GET

modele_new:
    path:     /new
    defaults: { _controller: "ChouettesBundle:Modele:new" }
    methods:  [GET, POST]

modele_edit:
    path:     /{id}/edit
    defaults: { _controller: "ChouettesBundle:Modele:edit" }
    methods:  [GET, POST]

modele_delete:
    path:     /{id}/delete
    defaults: { _controller: "ChouettesBundle:Modele:delete" }
    requirements:
      id: \d+

