chouettes_homepage:
    path:     /
    defaults: { _controller: ChouettesBundle:Default:index }

chouettes_doudous:
    path:     /doudous/{id}
    defaults: { _controller: ChouettesBundle:Default:doudous, id: 0 }

chouettes_bijoux:
    path:     /bijoux
    defaults: { _controller: ChouettesBundle:Default:bijoux }

chouettes_accessoires:
    path:     /accessoires
    defaults: { _controller: ChouettesBundle:Default:accessoires }

chouettes_about:
    path:     /about
    defaults: { _controller: ChouettesBundle:Default:about }

chouettes_contact:
    path:     /contact
    defaults: { _controller: ChouettesBundle:Default:contact }

